apiVersion: v1
kind: Service
metadata:
  name: site-nginx-clusterip-service
  labels:
    app: site-nginx
spec:
  type: ClusterIP
  selector:
    app: site-nginx
  ports:
  - port: 80
    targetPort: 80
