apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-deployment
spec:
  selector:
    matchLabels:
      app: site-deployment
  template:
    metadata:
      labels:
        app: site-deployment
    spec:
      containers:
      - name: site-deployment
        image: higorluisbarbosa/site-treinamento:v3
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
