apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: site-ingress
  labels:
    app.kubernetes.io/name: site-ingress
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: site-myhost.onmicrosoft.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: site-service
            port:
              number: 80
